In [56]:
Kanto =[73,67,43]
Johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

In [57]:
w1,w2,w3 = 0.3,0.2,0.5

In [58]:
weights = [w1,w2,w3]

In [59]:
def crop_yield(region,weights):
    result =0
    for x,w in zip(region,weights):
        result += x*w
    return result

In [60]:
crop_yield(Kanto,weights)

56.8

In [61]:
crop_yield(Johto,weights)

76.9

In [62]:
crop_yield(hoenn,weights)

81.9

In [63]:
crop_yield(sinnoh,weights)

57.699999999999996

In [64]:
crop_yield(unova,weights)

74.9

# Numpy

In [65]:
!pip install numpy

In [66]:
import numpy as np

In [67]:
Kanto = np.array([73,67,43])

In [68]:
Kanto

array([73, 67, 43])

In [69]:
weights = np.array([w1,w2,w3])

In [70]:
type (Kanto)

numpy.ndarray

In [71]:
type (weights)

numpy.ndarray

In [72]:
Kanto[2]

43

In [73]:
weights[0]

0.3

In [74]:
np.dot(kanto,weights)

NameError: name 'kanto' is not defined

In [ ]:
kanto * weights

In [ ]:
(kanto * weights).sum()

In [ ]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

In [ ]:
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [ ]:
%%time 
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

# {%%time} is used to compute the time taken to process the argument

In [ ]:
%%time
np.dot(arr1_np,arr2_np)

# Multi_dimentional Numpy arrays

In [ ]:
climate_data = np.array([[73,67,43],
                        [91,88,64],
                        [87,134,58],
                        [102,43,37],
                        [69,96,70]])

In [ ]:
climate_data

In [ ]:
# 2D array (matrix)
climate_data.shape

In [ ]:
weights

In [ ]:
weights.shape
# 1D array (vector)

In [ ]:
# 3D array
arr3 = np.array([
    [[11,12,13],
     [13,14,15]],
    
    [[15,16,17],
     [17,18,19.5]]])

In [ ]:
arr3.shape

In [ ]:
arr3.dtype

In [ ]:
weights.dtype


In [ ]:
climate_data.dtype

In [ ]:
climate_data

In [ ]:
np.dot(climate_data,weights)

In [ ]:
np.matmul(climate_data,weights)

In [ ]:
climate_data @ weights

# working with csv

In [ ]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

In [ ]:
climate_data = np.genfromtxt('climate.txt', delimiter =',' , skip_header =1 )

In [ ]:
climate_data

In [ ]:
climate_data.shape

In [ ]:
weights = np.array([0.3,0.2,0.5])

In [ ]:
yields = climate_data @ weights 

In [ ]:
yields

In [ ]:
yields.shape

In [ ]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)), axis =1)

In [ ]:
climate_results

In [ ]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt = '%.2f',
          header = 'temperature, rainfall,humidity,yield_apples',
          comments = '')

# arithmetic operations 

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]]
)

In [ ]:
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,13]
])

In [ ]:
arr2 + arr3

In [ ]:
arr2 +3

In [ ]:
arr3- arr2

In [ ]:
arr2 / 2

In [ ]:
arr2 * arr3

In [ ]:
arr2 % 4

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]
])

In [ ]:
arr2.shape

In [ ]:
arr4 = np.array([4,5,6,7])

In [ ]:
arr4.shape

In [ ]:
arr2 + arr4

In [ ]:
arr5 = np.array([7,8])

In [ ]:
arr5.shape

In [ ]:
arr2 + arr5

In [ ]:
arr1 = np.array([[1,2,3,] , [3,4,5]])
arr2 = np.array([[2,2,3], [1,2,5]])

In [ ]:
(arr1 == arr2).dtype

In [ ]:
arr1 != arr2

In [ ]:
arr1 >= arr2

In [ ]:
arr1 < arr2

In [ ]:
(arr1==arr2).sum()

# Array Indexing and Slicing

In [75]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [76]:
arr3.shape

(3, 2, 4)

In [77]:
arr3[1,1,2]

36.0

In [78]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [79]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [81]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [82]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [83]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [84]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [85]:
# Using too many indices
arr3[1,3,2,1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

## Other ways of creating Numpy arrays

Numpy also provides some handy functions to create arrays of desired shapes with fixed or random values. Check out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more.

In [87]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
# Random vector
np.random.rand(5)

array([0.74176016, 0.17229278, 0.95977986, 0.1649231 , 0.39827904])

In [91]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 0.4429792 , -0.69516272, -0.5764653 ],
       [ 0.13736663, -1.21872884,  0.01280805]])

In [92]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [93]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [94]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])